export const NIGERIAN_BANKS = [
  'Access Bank PLC',
  'Access Diamond Bank',
  'Citibank Nigeria Limited',
  'Ecobank Nigeria PLC',
  'Fidelity Bank PLC',
  'First Bank of Nigeria Limited',
  'First City Monument Bank (FCMB)',
  'Globus Bank Limited',
  'Guaranty Trust Bank (GTBank)',
  'Heritage Bank PLC',
  'Jaiz Bank PLC',
  'Keystone Bank Limited',
  'Kuda Bank',
  'Lotus Bank',
  'Moniepoint Microfinance Bank',
  'Opay',
  'Paga',
  'Palmpay',
  'Parallex Bank Limited',
  'Polaris Bank Limited',
  'PremiumTrust Bank Limited',
  'Providus Bank Limited',
  'Stanbic IBTC Bank PLC',
  'Standard Chartered Bank Nigeria',
  'Sterling Bank PLC',
  'SunTrust Bank Nigeria Limited',
  'TajBank Limited',
  'Titan Trust Bank Limited',
  'Union Bank of Nigeria PLC',
  'United Bank for Africa (UBA)',
  'Unity Bank PLC',
  'VFD Microfinance Bank',
  'Wema Bank PLC',
  'Zenith Bank PLC',
];
