-- 4CoreFinSupport — Continuous audit chain verification
-- Migration 034: pg_cron job that verifies the audit hash chain every 5 minutes
-- per business unit, inserts verification records, and flags breaks.

-- Verification log table: one row per verified BU per run
CREATE TABLE IF NOT EXISTS audit_verification_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_unit TEXT NOT NULL,
  verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  chain_valid BOOLEAN NOT NULL,
  broken_index INTEGER NULL,
  notes TEXT NULL
);

-- Index for cleanup
CREATE INDEX IF NOT EXISTS idx_audit_verification_bucket ON audit_verification_log (business_unit, verified_at DESC);

-- Stored procedure: verify the audit chain for a single business unit.
-- Returns the first broken index (or NULL if the chain is valid).
CREATE OR REPLACE FUNCTION verify_audit_chain_for_bu(bu_filter TEXT)
RETURNS TABLE (broken_index INTEGER, chain_valid BOOLEAN) AS $$
DECLARE
  logs RECORD;
  prev_hash TEXT := '';
  idx INTEGER := 0;
  broken_idx INTEGER := NULL;
BEGIN
  -- Fetch logs for this BU, oldest-first, limited to a reasonable window.
  -- The function can be called with '' (empty) to verify the global chain,
  -- or with a BU string like 'ALPHA' to verify that BU only.
  FOR logs IN
    SELECT id, timestamp, ticket_id, actor, role, action, details, hash, previous_hash
    FROM audit_logs
    WHERE (bu_filter IS NULL OR bu_filter = '' OR tenant_id = bu_filter)
    ORDER BY timestamp ASC, id ASC
  LOOP
    idx := idx + 1;
    -- First entry: previous_hash should be empty
    IF idx = 1 THEN
      IF (logs.previous_hash || '') != '' THEN
        broken_idx := idx;
        EXIT;
      END IF;
    ELSE
      -- Subsequent entries: previous_hash must match the prior entry's hash
      IF (logs.previous_hash || '') != prev_hash THEN
        broken_idx := idx;
        EXIT;
      END IF;
    END IF;
    prev_hash := logs.hash;
  END LOOP;

  IF broken_idx IS NULL THEN
    chain_valid := TRUE;
    INSERT INTO audit_verification_log (business_unit, verified_at, chain_valid, notes)
    VALUES (bu_filter, NOW(), TRUE, 'Chain verified OK');
  ELSE
    chain_valid := FALSE;
    INSERT INTO audit_verification_log (business_unit, verified_at, chain_valid, notes)
    VALUES (bu_filter, NOW(), FALSE, 'Chain broken at audit_log #' || broken_idx);
  END IF;

  RETURN QUERY SELECT broken_idx, chain_valid;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- pg_cron job: verify the global audit chain every 5 minutes.
-- To verify a specific BU, replace NULL with the BU name, e.g. 'ALPHA'.
SELECT cron.schedule('verify-audit-chain-global', '*/5 * * * *', '
  SELECT set_config('app.tenant_id', NULL, false);
  PERFORM verify_audit_chain_for_bu(NULL);
');

-- Also schedule per-business-unit verification every 15 minutes.
-- Adjust the BU list as new tenants are created.
-- SELECT cron.schedule('verify-audit-chain-alpha', '*/15 * * * *', '
--   PERFORM verify_audit_chain_for_bu("ALPHA");
-- ');
-- SELECT cron.schedule('verify-audit-chain-beta', '*/15 * * * *', '
--   PERFORM verify_audit_chain_for_bu("BETA");
-- ');